### ISSUE TITLE
[Feature request] Show estimated time

### ISSUE THREAD

**Issue by janis-ax** [eyal0/OctoPrint-PrintTimeGenius#178]
I think it would be nice if it display not only the duration also the estimated time when a print is done. 

E.g.: Duration 3h Estimated time: 10:15 AM

**Comment by eyal0** [comment]
That would be possible but it ought to be in a different plugin, because it is functionality that doesn't depend on PTG.  So there could be PTG, providing good estimates, and another plugin, which causes the estimate to display as a time.

There might already be plugins for that, though.  I know that there was some plugin that would send ETA to the printer, it was called M73 or M74 or something...

**Comment by eyal0** [comment]
Here's one: https://plugins.octoprint.org/plugins/octoprint-eta/

That will put the "ETA" on the screen.  Try that and let me know how it integrates together with PTG.

**Comment by janis-ax** [comment]
> 
> 
> Here's one: https://plugins.octoprint.org/plugins/octoprint-eta/
> 
> That will put the "ETA" on the screen. Try that and let me know how it integrates together with PTG.

Yeah, work's fine !!
