### ISSUE TITLE
Estimate way out

### ISSUE THREAD

**Issue by mrtmsmith89** [eyal0/OctoPrint-PrintTimeGenius#270]
Not used to this github so please forgive me if I don't post correctly.

I've been doing some benchys, and the plugin is suggesting 1:00:17 when in fact the print is around the 1:50:00 mark. One print stopped dead half way through when it was past the 100% print time genius expected, but don't think that's related, let me know if it is.

I've downloaded the log, but it means absolutely nothing to me, anyone care to take a look
[plugin_PrintTimeGenius_engine.log](https://github.com/eyal0/OctoPrint-PrintTimeGenius/files/7613424/plugin_PrintTimeGenius_engine.log)
?

**Comment by eyal0** [comment]
There are many prints in your file so I'm not sure which one you mean.  But I can see that the file `/home/pi/.octoprint/uploads/Regular Makes/3DBenchyPLA+1hr50.gcode` was expected to take 6198.698853978463 seconds, which is about 1h43m.  Then it seems that it was multiplied by some really weird factors due to previous prints taking generally much faster than the calculation.

Consider deleting all the compensation factors and starting over.

https://github.com/eyal0/OctoPrint-PrintTimeGenius/wiki/Common-problems#printing-time-is-way-off

Re-open this issue if the problem persists, thanks!
