### ISSUE TITLE
Issue analyzing with two print heads

### ISSUE THREAD

**Issue by Don-Swanson** [eyal0/OctoPrint-PrintTimeGenius#39]
Before reporting, check if your problem is here:
https://github.com/eyal0/OctoPrint-PrintTimeGenius/wiki/Common-problems

Please fill this out:

OctoPrint Version: 1.3.9rc3 

PrintTimeGenius Version (if you know): 1.0.6

What did you try: Trying to analyze/print a file with command to use both print heads on a dual print head extruder.

What happenned: fails to analyze the gcode for the second print head

What did you expect to happen: analyze the file for both print heads.

There seems to be an issue or some kind of conflict when I try to print a file that is setup for dual extrusion. As seen in image # 1 where PrintTimeGenius is disabled, octoprint correctly analyzed the filament usage for the second print head in addition to the first. In image # 2 where PrintTimeGenius is enabled, it fails to account for what is being printed with the second print head. The biggest issue this causes is since filament usage is not calculated for the second print head, it screws up my filament inventory tracked by filament manager.

If relevant, upload the PrintTimeGenius log and any problematic gcode files (you might need to rename them).
![1](https://user-images.githubusercontent.com/32144818/42855668-351757ea-8a07-11e8-9f3d-36a4a86ae384.png)
![2](https://user-images.githubusercontent.com/32144818/42855669-352c5708-8a07-11e8-8ef2-0112b7d75cca.png)

**Comment by eyal0** [comment]
I'll work on this. I've never worked with dual extrusion before. Do you have a sample gcode file that you can attach to this issue?

**Comment by TheEagle13** [comment]
See Attached
[floor_stand2.zip](https://github.com/eyal0/OctoPrint-PrintTimeGenius/files/2204200/floor_stand2.zip)

**Comment by eyal0** [comment]
Thanks, that great!  I can see in the file that you sent that Simplify3D doesn't report the filament length per tool.  Bummer.  OctoPrint's built-in calculations are able to do that, however, so I think that it might be better to just use OctoPrint's math.

I'll remove the filament length analysis section from the script.

Do you have samples of Cura330, Cura15, or Slic3r gcode with multiple filaments?  That would help me fix those, too.

**Comment by TheEagle13** [comment]
Unfortunately I do not. Slic3r and Cura do not function properly for IDEX Printers yet.

**Comment by eyal0** [comment]
@TheEagle13 I'm looking at the gcode you sent, trying to figure it out.  Looks like it travels to X-40 at some point.  Is that on purpose?  Looks like it goes there and dumps out some filament at the start of a print.

**Comment by TheEagle13** [comment]
That is specific to just the Formbot T-Rex 2+ printers since they have actual "trash bins" that they run to and wipe themselves so that you don't have to print ooze shields like other printers use to prevent ooze on the print. So the starting gcode for mine in particular is probably going to be drastically different from others, but the actual printing g-code is going to be mostly similar, except for the homing of the un-used print head since it is an IDEX printer.

**Comment by eyal0** [comment]
I discovered that big X-40 while working on calculating the print dimensions. It wasn't causing OctoPrint problems but for me it was. Turned out that OctoPrint only counts the volume of the model as the area where both extrusion and movement are happening together. Once I did the same, my model dimension calculations became the same as OctoPrint.

OctoPrint uses the information to give a warning when users try to print outside the bounds of the printer.

Anyway, glad that it works!
