### ISSUE TITLE
Feature Request: Option to disable in depth analysis for large files

### ISSUE THREAD

**Issue by TheEagle13** [eyal0/OctoPrint-PrintTimeGenius#55]
This is a feature request to enable an option to not have PTG do an in-depth analysis of large gcode files (over a specific size). I am running into an issue where some of my larger prints (70-150 mb gcode files) are taking well over several hours to be analyzed by PTG causing a large delay before I can start to print them. I know with the default OctoPrint estimator, it would only take about 20 minutes for such a large file, but PTG is taking several hours (I gave up monitoring to count the full amount of time)

**Comment by eyal0** [comment]
That is surprising because the built-in in analyzer from OctoPrint is usually much slower than mine. In fact, I'm working on removing the built in one and only using mine.

https://github.com/eyal0/OctoPrint-PrintTimeGenius/issues/49

Can you provide an example large gcode file so that I can check that marlin-calc is actually slower than OctoPrint. It should be faster! Maybe you can use a medium-large gcode file and look in the log at the timestamps to check how long each analyser is taking?

**Comment by eyal0** [comment]
By the way, if you start printing before analysis is done, analysis gets cancelled. So maybe there is no need to ship analysis of large files because they get cancelled anyway.

Also, PTG reports the progress after each phase, so if the built-in completes but the marlin-calc is cancelled, we'll still use the results from the former.

marlin-calc is usually like 10 times faster than built-in. I'm curious why you saw something else. Maybe I compiled it wrong?

**Comment by TheEagle13** [comment]
Thanks for the response. I didn't think to check the logs to compare times. I will do that tomorrow.

The reason I'm unable to start printing is because my Filament manager plug in requires the analysis to be completed before it will let you print. I assume it's so that you can make sure you have enough Filament for a print before starting. Maybe I should look into seeing if I can bypass that and still have accurate Filament usage since I have a Filament sensor attached to the PI.

**Comment by eyal0** [comment]
To compare the speed, log in to the system on which you run OctoPrint and try this:

`time /home/pi/oprint/bin/python /home/pi/oprint/bin/octoprint analysis gcode ~/.octoprint/uploads/floor_stand2.gcode`

versus

`time /home/pi/oprint/lib/python2.7/site-packages/octoprint_PrintTimeGenius/analyzers/analyze_progress.py marlin-calc ~/.octoprint/uploads/floor_stand2.gcode`

I expect the former to be slower.  Let me know if it isn't!

**Comment by TheEagle13** [comment]
You are correct about the drastic analysis time differences. But this brings up a new question... Since you disabled the filament calculation since it wasn't working for dual extruders, does that mean that your analysis runs for print time, then octoprint has to run it's analysis anyway for filament usage?

If so, that would explain why I'm experiencing double the times on Octoprint before I can start printing, since I am now waiting for 2 processes to complete.

**Comment by eyal0** [comment]
Yes, though not quite double because the Marlin based analysis is faster.

It's not just because of the dual extruder that I need to do the built in analysis. It's because it provides printing bounds and I didn't have that.

I added printing bounds and volume calculation and dual exruder support into the latest Marlin calc. With that, I can safely turn off the built-in analysis and use just marlin-calc, which will handle everything and faster and more accurately.

**Comment by TheEagle13** [comment]
Right. I'm exaggerating of course. Have you added that into the latest plugin version? If not, do you have a beta you'd like for me to test out for you?

**Comment by eyal0** [comment]
Yes. Please try:

https://github.com/eyal0/OctoPrint-PrintTimeGenius/archive/dev.zip

**Comment by TheEagle13** [comment]
Can Confirm, that works LIGHTYEARS Better for my needs. Thank you very much! 
Now, How do I go about buying you a drink of your choice?

**Comment by eyal0** [comment]
No thanks, earning money will turn this hobby into a job and I won't allow that.  But thanks for your offer!

Did you try to enable analysis while printing?  Does it work?

Also, I put in effort to make sure that dual extruder is supported s it should calculate the filament length and volume correctly.  Let me know if you see wrong answers.

Enjoy!
